name:                my-xmonad
version:             0.1.0.0
github:              "JBarberU/my-xmonad"
license:             BSD-3-Clause
author:              "John Barbero Unenge"
maintainer:          "git@lsrkttn.com"
copyright:           "2024 John Barbero Unenge"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JBarberU/my-xmonad#readme>

dependencies:
- base >= 4.7 && < 5
- hostname >= 1.0
- xmobar >= 0.48
- xmonad >= 0.18
- xmonad-contrib >= 0.18
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  xmonad:
    main:                xmonad.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-xmonad
  xmobar:
    main:               xmobar.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-xmonad

tests:
  my-xmonad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-xmonad
